- added preliminary support for pthread in libc_r; however, it seems to be   missing pthread_sigwait()

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1874,7 +1874,54 @@ EOF
       LIBP="-lpthread"
 else
   echo "$ac_t""no" 1>&6
-echo "configure: warning: Compiling without pthread support" 1>&2
+echo "configure: warning: No libpth detected - trying libc_r" 1>&2
+       echo $ac_n "checking for pthread_create in -lc_r""... $ac_c" 1>&6
+echo "configure:1880: checking for pthread_create in -lc_r" >&5
+ac_lib_var=`echo c_r'_'pthread_create | sed 'y%./+-%__p_%'`
+if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  ac_save_LIBS="$LIBS"
+LIBS="-lc_r  $LIBS"
+cat > conftest.$ac_ext <<EOF
+#line 1888 "configure"
+#include "confdefs.h"
+/* Override any gcc2 internal prototype to avoid an error.  */
+/* We use char because int might match the return type of a gcc2
+    builtin and then its argument prototype would still apply.  */
+char pthread_create();
+
+int main() {
+pthread_create()
+; return 0; }
+EOF
+if { (eval echo configure:1899: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+  rm -rf conftest*
+  eval "ac_cv_lib_$ac_lib_var=yes"
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  eval "ac_cv_lib_$ac_lib_var=no"
+fi
+rm -f conftest*
+LIBS="$ac_save_LIBS"
+
+fi
+if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
+  echo "$ac_t""yes" 1>&6
+  cat >> confdefs.h <<\EOF
+#define HAVE_PTHREADS 1
+EOF
+
+         _have_pthread=yes
+         CFLAGS="${CFLAGS} -D_REENTRANT"
+         LIBP="-lc_r"
+else
+  echo "$ac_t""no" 1>&6
+echo "configure: warning: Compiling without multithread support" 1>&2
+fi
+
 fi
 
 fi
